### PR TITLE
Add <BarComponent />

### PR DESCRIPTION
**Pull request by rubenmoya**
## Description
This PR adds the bar chart, but still WIP 🐣 .

As always, feedback is appreciated :)

## Motivation and Context
I was pretty bored, last time I added a chart you were really nice to me so here I am again!

## How Has This Been Tested?
It's still in progress, I'm having some problems with the tests (see https://github.com/eventbrite/britecharts-react/issues/45), but my goal is to have the same tests as the other two components.

## Screenshots (if appropriate):
screen shot 2017-12-02 at 12 15 09
screen shot 2017-12-02 at 12 15 16
screen shot 2017-12-02 at 12 15 36

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by miglesiasEB** [comment]
Soo.... it seems this is due to a limitation in our test environment, as it is not rendering the thing. The text wrapping function tries to find a node in the DOM, and with Jest we cannot find it there.

I think the solution will be to do some defensive programming in that function in the original Bar chart in Britecharts. 

I will take it from here, thanks a lot Ruben!!

**Comment by rubenmoya** [comment]
Thank you! If there's anything else I can do let me know :)

**Comment by Golodhros** [comment]
Here's the fix in Britecharts: https://github.com/eventbrite/britecharts/pull/439

Bummer that I don't know if something else would break...

**Comment by rubenmoya** [comment]
So, I've been reading a little bit about this, it seems like `jsdom` does not support `getComputedTextLength` or maybe it's because `tspan.node()` it's a `HTMLUnknownElement`, maybe if it was an `SVGElement` it would work?

The thing is, I've found a workaround so we don't have to touch Britecharts, it works by adding a setup file to jest, and adding the function to the `Element` prototype.

```
window.Element.prototype.getComputedTextLength = () => 200;
```

What do you think? Or maybe we could do some more research about why it's returning a `HTMLUnknownElement`

**Comment by Golodhros** [comment]
Thanks for taking a look at this!
Well, I am OK with adding that check in Britecharts. It is not a problem.
If that doesn't work, then we could touch the jest setup as you mention.

Thanks again!

**Comment by rubenmoya** [comment]
Perfect! Do you want me to finish it after eventbrite/britecharts#439 is merged?

**Comment by Golodhros** [comment]
Don't worry, I take care. 

Thanks!

**Comment by Golodhros** [comment]
It didn't work :(

I have pushed a PR with some updates in https://github.com/eventbrite/britecharts-react/pull/70
If your workaround @rubenmoya  works, let's go for it!

Thanks!

**Comment by rubenmoya** [comment]
Closing this in favor of #70

**Pull request closed without merging**
